Name:               prometheus-monitoring-kube-prometheus-prometheus
Namespace:          monitoring
CreationTimestamp:  Sun, 19 Oct 2025 12:53:15 -0500
Selector:           app.kubernetes.io/instance=monitoring-kube-prometheus-prometheus,app.kubernetes.io/managed-by=prometheus-operator,app.kubernetes.io/name=prometheus,operator.prometheus.io/name=monitoring-kube-prometheus-prometheus,operator.prometheus.io/shard=0,prometheus=monitoring-kube-prometheus-prometheus
Labels:             app=kube-prometheus-stack-prometheus
                    app.kubernetes.io/instance=monitoring-kube-prometheus-prometheus
                    app.kubernetes.io/managed-by=prometheus-operator
                    app.kubernetes.io/name=prometheus
                    app.kubernetes.io/part-of=kube-prometheus-stack
                    app.kubernetes.io/version=78.3.2
                    chart=kube-prometheus-stack-78.3.2
                    heritage=Helm
                    managed-by=prometheus-operator
                    operator.prometheus.io/mode=server
                    operator.prometheus.io/name=monitoring-kube-prometheus-prometheus
                    operator.prometheus.io/shard=0
                    prometheus=monitoring-kube-prometheus-prometheus
                    release=monitoring
Annotations:        meta.helm.sh/release-name: monitoring
                    meta.helm.sh/release-namespace: monitoring
                    prometheus-operator-input-hash: 14330799341099063205
Replicas:           1 desired | 1 total
Update Strategy:    RollingUpdate
Pods Status:        1 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           app.kubernetes.io/instance=monitoring-kube-prometheus-prometheus
                    app.kubernetes.io/managed-by=prometheus-operator
                    app.kubernetes.io/name=prometheus
                    app.kubernetes.io/version=3.7.1
                    operator.prometheus.io/name=monitoring-kube-prometheus-prometheus
                    operator.prometheus.io/shard=0
                    prometheus=monitoring-kube-prometheus-prometheus
  Annotations:      kubectl.kubernetes.io/default-container: prometheus
  Service Account:  monitoring-kube-prometheus-prometheus
  Init Containers:
   init-config-reloader:
    Image:      quay.io/prometheus-operator/prometheus-config-reloader:v0.86.1
    Port:       8081/TCP
    Host Port:  0/TCP
    Command:
      /bin/prometheus-config-reloader
    Args:
      --watch-interval=0
      --listen-address=:8081
      --config-file=/etc/prometheus/config/prometheus.yaml.gz
      --config-envsubst-file=/etc/prometheus/config_out/prometheus.env.yaml
      --watched-dir=/etc/prometheus/rules/prometheus-monitoring-kube-prometheus-prometheus-rulefiles-0
    Environment:
      POD_NAME:   (v1:metadata.name)
      SHARD:     0
    Mounts:
      /etc/prometheus/config from config (rw)
      /etc/prometheus/config_out from config-out (rw)
      /etc/prometheus/rules/prometheus-monitoring-kube-prometheus-prometheus-rulefiles-0 from prometheus-monitoring-kube-prometheus-prometheus-rulefiles-0 (rw)
  Containers:
   prometheus:
    Image:      quay.io/prometheus/prometheus:v3.7.1
    Port:       9090/TCP
    Host Port:  0/TCP
    Args:
      --config.file=/etc/prometheus/config_out/prometheus.env.yaml
      --web.enable-lifecycle
      --web.external-url=http://monitoring-kube-prometheus-prometheus.monitoring:9090
      --web.route-prefix=/
      --storage.tsdb.retention.time=10d
      --storage.tsdb.path=/prometheus
      --storage.tsdb.wal-compression
      --web.config.file=/etc/prometheus/web_config/web-config.yaml
    Liveness:     http-get http://:http-web/-/healthy delay=0s timeout=3s period=5s #success=1 #failure=6
    Readiness:    http-get http://:http-web/-/ready delay=0s timeout=3s period=5s #success=1 #failure=3
    Startup:      http-get http://:http-web/-/ready delay=0s timeout=3s period=60s #success=1 #failure=10
    Environment:  <none>
    Mounts:
      /etc/prometheus/certs from tls-assets (ro)
      /etc/prometheus/config_out from config-out (ro)
      /etc/prometheus/rules/prometheus-monitoring-kube-prometheus-prometheus-rulefiles-0 from prometheus-monitoring-kube-prometheus-prometheus-rulefiles-0 (rw)
      /etc/prometheus/web_config/web-config.yaml from web-config (ro,path="web-config.yaml")
      /prometheus from prometheus-monitoring-kube-prometheus-prometheus-db (rw)
   config-reloader:
    Image:      quay.io/prometheus-operator/prometheus-config-reloader:v0.86.1
    Port:       8080/TCP
    Host Port:  0/TCP
    Command:
      /bin/prometheus-config-reloader
    Args:
      --listen-address=:8080
      --reload-url=http://127.0.0.1:9090/-/reload
      --config-file=/etc/prometheus/config/prometheus.yaml.gz
      --config-envsubst-file=/etc/prometheus/config_out/prometheus.env.yaml
      --watched-dir=/etc/prometheus/rules/prometheus-monitoring-kube-prometheus-prometheus-rulefiles-0
    Environment:
      POD_NAME:   (v1:metadata.name)
      SHARD:     0
    Mounts:
      /etc/prometheus/config from config (rw)
      /etc/prometheus/config_out from config-out (rw)
      /etc/prometheus/rules/prometheus-monitoring-kube-prometheus-prometheus-rulefiles-0 from prometheus-monitoring-kube-prometheus-prometheus-rulefiles-0 (rw)
  Volumes:
   config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  prometheus-monitoring-kube-prometheus-prometheus
    Optional:    false
   tls-assets:
    Type:        Projected (a volume that contains injected data from multiple sources)
    SecretName:  prometheus-monitoring-kube-prometheus-prometheus-tls-assets-0
    Optional:    false
   config-out:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
   prometheus-monitoring-kube-prometheus-prometheus-rulefiles-0:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      prometheus-monitoring-kube-prometheus-prometheus-rulefiles-0
    Optional:  false
   web-config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  prometheus-monitoring-kube-prometheus-prometheus-web-config
    Optional:    false
   prometheus-monitoring-kube-prometheus-prometheus-db:
    Type:          EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:        
    SizeLimit:     <unset>
  Node-Selectors:  <none>
  Tolerations:     <none>
Volume Claims:     <none>
Events:            <none>
